version: '2.1'

services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    links:
      - php
  php:
    extends:
      file: docker-compose.yml
      service: php
    links:
      - redis
      - postgres
  postgres:
    image: postgres:12.1
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/conf:/etc/postgresql/
    env_file:
      - ./../.env
    environment:
      POSTGRES_DB: lshop
      POSTGRES_USER: lshop
      POSTGRES_PASSWORD: lshop
  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/var/lib/redis

volumes:
  postgres: